# Welcome to SkMobChip

settings:
  # Enable this if you would like to see more verbose debug messages
  debug: false

  # Enable this to automatically check for SkMobChip updates
  # Disable this if you do not want to check for updates, or it takes too long/has issues checking
  update-checker: true
