blank_issues_enabled: false
contact_links:
  - name: 🦆 skUnity Discord
    url: https://discord.gg/skript
    about: For general help with SkMobChip join skUnity's Discord
  - name: 🚰 SpigotMC Resource
    url: https://www.spigotmc.org/resources/NOT-YET
    about: Read about SkMobChip!
